import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1770643610307 implements MigrationInterface {
    name = 'Init1770643610307'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "post_image" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "postId" integer, CONSTRAINT "PK_0c74d0ac8869bc3a3cbaa3ec55d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_668c9fb892f2accb872670c7b1" ON "post_image" ("postId") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "content" text NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "postId" integer NOT NULL, "parentId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e8d7c49f218ebb14314fdb374" ON "comments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8770bd9030a3d13c5f79a7d2e8" ON "comments" ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4367f08021b501ba78f98ae01" ON "comments" ("postId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "bookmark" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "tripRouteId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7fbf4a865ba38a590bb9239814" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f0a7140c8d15ee5cdd0b36e1de" ON "bookmark" ("userId", "tripRouteId") `);
        await queryRunner.query(`CREATE TYPE "public"."trip_route_item_type_enum" AS ENUM('spot', 'food', 'cafe', 'stay', 'activity')`);
        await queryRunner.query(`CREATE TABLE "trip_route_item" ("id" SERIAL NOT NULL, "type" "public"."trip_route_item_type_enum" NOT NULL, "order" integer NOT NULL, "recommendedLevel" integer NOT NULL, "title" character varying NOT NULL, "description" text, "imageUrl" character varying, "lat" double precision, "lng" double precision, "address" character varying, "startTime" character varying, "endTime" character varying, "externalUrl" character varying, "dayId" integer, CONSTRAINT "PK_0334ae6f47833c1c22eeccad762" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_98346f7a760e7de5ee79c9325e" ON "trip_route_item" ("dayId", "order") `);
        await queryRunner.query(`CREATE TABLE "trip_route_day" ("id" SERIAL NOT NULL, "dayNumber" integer NOT NULL, "title" character varying, "note" text, "tripRouteId" integer, CONSTRAINT "PK_8882d62a7945161aac53e64783e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_374668b8bdcb37409c5a47acfc" ON "trip_route_day" ("tripRouteId", "dayNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."spots_imagesource_enum" AS ENUM('UNSPLASH', 'KTO', 'OWNER', 'USER', 'ETC')`);
        await queryRunner.query(`CREATE TABLE "spots" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NOT NULL, "note" character varying, "imageUrl" character varying(255), "imageSource" "public"."spots_imagesource_enum", "imageCredit" character varying, "address" character varying, "externalUrl" character varying, "isRecommended" boolean NOT NULL DEFAULT false, "destinationId" integer NOT NULL, CONSTRAINT "UQ_0c9421c96c6947244a7e082bb84" UNIQUE ("slug"), CONSTRAINT "PK_cc8c0341ef60619746e42815cf4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3dd7c4dfa4c2fe57fa5894ab5" ON "spots" ("destinationId", "id") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "slug" character varying NOT NULL, "label" character varying NOT NULL, CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b3aa10c29ea4e61a830362bd25" ON "tags" ("slug") `);
        await queryRunner.query(`CREATE TABLE "trip_route" ("id" SERIAL NOT NULL, "slug" character varying NOT NULL, "region" character varying NOT NULL, "title" character varying NOT NULL, "summary" character varying(300) NOT NULL, "days" integer NOT NULL, "bookmarkCount" integer NOT NULL DEFAULT '0', "destinationId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7403b82a4b74cc97d12e3c06fa4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cd9bb7e79c38564ff28d5674a8" ON "trip_route" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c9bab3324bd8bcd18a0184fc0" ON "trip_route" ("region") `);
        await queryRunner.query(`CREATE INDEX "IDX_78c7117b54e48f4a8ae2acb054" ON "trip_route" ("destinationId", "bookmarkCount") `);
        await queryRunner.query(`CREATE TYPE "public"."destinations_province_enum" AS ENUM('SEOUL_GYEONGGI', 'GANGWON', 'CHUNGCHEONG', 'JEOLLA', 'GYEONGSANG', 'JEJU')`);
        await queryRunner.query(`CREATE TYPE "public"."destinations_imagesource_enum" AS ENUM('UNSPLASH', 'KTO', 'OWNER', 'USER', 'ETC')`);
        await queryRunner.query(`CREATE TABLE "destinations" ("id" SERIAL NOT NULL, "slug" character varying(100) NOT NULL, "province" "public"."destinations_province_enum" NOT NULL, "name" character varying NOT NULL, "score" double precision NOT NULL, "imageUrl" character varying NOT NULL, "imageSource" "public"."destinations_imagesource_enum", "imageCredit" character varying, "latitude" numeric NOT NULL, "longitude" numeric NOT NULL, "summary" character varying NOT NULL, "reviewCount" integer NOT NULL DEFAULT '0', "rank" integer NOT NULL, "food" integer NOT NULL, "transport" integer NOT NULL, "safety" integer NOT NULL, "loneliness" integer NOT NULL, CONSTRAINT "UQ_30864aeaf404f4a6d3f816bd8c5" UNIQUE ("slug"), CONSTRAINT "UQ_8ec7648e4654df2a195dd516ba9" UNIQUE ("rank"), CONSTRAINT "PK_69c5e8db964dcb83d3a0640f3c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c954d0d1472ab3e9f68d19b19f" ON "destinations" ("province", "rank") `);
        await queryRunner.query(`CREATE TABLE "post_likes" ("id" SERIAL NOT NULL, "postId" integer NOT NULL, "userId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e4ac7cb9daf243939c6eabb2e0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6999d13aca25e33515210abaf1" ON "post_likes" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37d337ad54b1aa6b9a44415a49" ON "post_likes" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_30ee85070afe5b92b5920957b1" ON "post_likes" ("postId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."posts_type_enum" AS ENUM('REVIEW', 'FREE', 'QUESTION')`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "rating" double precision, "region" character varying, "type" "public"."posts_type_enum" NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "thumbnailUrl" character varying, "isDeleted" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "destinationId" integer, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c0accd394270dbf27ce74d0bb" ON "posts" ("userId", "isDeleted", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e854e28011a0131c68e49ac091" ON "posts" ("isDeleted", "type", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."users_provider_enum" AS ENUM('apple', 'kakao', 'google', 'naver')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying, "provider" "public"."users_provider_enum" NOT NULL, "providerId" character varying NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "nickName" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "refreshToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_44b6d4cb3fe916de38974ed9c2f" UNIQUE ("nickName"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ae9a93b13bce1425823c8ecd07" ON "users" ("provider", "providerId") `);
        await queryRunner.query(`CREATE TABLE "spot_tags" ("spotsId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_8589f62e062167aa2a560acdb00" PRIMARY KEY ("spotsId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_804eb6f8cbba6406bbad3aa3d1" ON "spot_tags" ("spotsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_164c1775ebf02e05ca509aa013" ON "spot_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "trip_route_tags" ("tripRouteId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_a8e3cd5956f47a296235737c910" PRIMARY KEY ("tripRouteId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15c08232edf72deb0ad95e2382" ON "trip_route_tags" ("tripRouteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b72d926b23113c0413f937dc3" ON "trip_route_tags" ("tagsId") `);
        await queryRunner.query(`ALTER TABLE "post_image" ADD CONSTRAINT "FK_668c9fb892f2accb872670c7b1e" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_e389fc192c59bdce0847ef9ef8b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_e87a6e55c202a10f72bc8a75f4f" FOREIGN KEY ("tripRouteId") REFERENCES "trip_route"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_route_item" ADD CONSTRAINT "FK_f318b2c0fe28596b4e165476050" FOREIGN KEY ("dayId") REFERENCES "trip_route_day"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_route_day" ADD CONSTRAINT "FK_0c7b0af5140c6506ea41c03592f" FOREIGN KEY ("tripRouteId") REFERENCES "trip_route"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spots" ADD CONSTRAINT "FK_23eaf2d0a7ef92c667a8c2050a3" FOREIGN KEY ("destinationId") REFERENCES "destinations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_route" ADD CONSTRAINT "FK_112c5b1b524d13284eef8669823" FOREIGN KEY ("destinationId") REFERENCES "destinations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_0edd7303f9bfed050aa4935789e" FOREIGN KEY ("destinationId") REFERENCES "destinations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spot_tags" ADD CONSTRAINT "FK_804eb6f8cbba6406bbad3aa3d10" FOREIGN KEY ("spotsId") REFERENCES "spots"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "spot_tags" ADD CONSTRAINT "FK_164c1775ebf02e05ca509aa0135" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_route_tags" ADD CONSTRAINT "FK_15c08232edf72deb0ad95e23827" FOREIGN KEY ("tripRouteId") REFERENCES "trip_route"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "trip_route_tags" ADD CONSTRAINT "FK_1b72d926b23113c0413f937dc3a" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "trip_route_tags" DROP CONSTRAINT "FK_1b72d926b23113c0413f937dc3a"`);
        await queryRunner.query(`ALTER TABLE "trip_route_tags" DROP CONSTRAINT "FK_15c08232edf72deb0ad95e23827"`);
        await queryRunner.query(`ALTER TABLE "spot_tags" DROP CONSTRAINT "FK_164c1775ebf02e05ca509aa0135"`);
        await queryRunner.query(`ALTER TABLE "spot_tags" DROP CONSTRAINT "FK_804eb6f8cbba6406bbad3aa3d10"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_0edd7303f9bfed050aa4935789e"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_ae05faaa55c866130abef6e1fee"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "trip_route" DROP CONSTRAINT "FK_112c5b1b524d13284eef8669823"`);
        await queryRunner.query(`ALTER TABLE "spots" DROP CONSTRAINT "FK_23eaf2d0a7ef92c667a8c2050a3"`);
        await queryRunner.query(`ALTER TABLE "trip_route_day" DROP CONSTRAINT "FK_0c7b0af5140c6506ea41c03592f"`);
        await queryRunner.query(`ALTER TABLE "trip_route_item" DROP CONSTRAINT "FK_f318b2c0fe28596b4e165476050"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_e87a6e55c202a10f72bc8a75f4f"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_e389fc192c59bdce0847ef9ef8b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749"`);
        await queryRunner.query(`ALTER TABLE "post_image" DROP CONSTRAINT "FK_668c9fb892f2accb872670c7b1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b72d926b23113c0413f937dc3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15c08232edf72deb0ad95e2382"`);
        await queryRunner.query(`DROP TABLE "trip_route_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_164c1775ebf02e05ca509aa013"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_804eb6f8cbba6406bbad3aa3d1"`);
        await queryRunner.query(`DROP TABLE "spot_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae9a93b13bce1425823c8ecd07"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e854e28011a0131c68e49ac091"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c0accd394270dbf27ce74d0bb"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TYPE "public"."posts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30ee85070afe5b92b5920957b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37d337ad54b1aa6b9a44415a49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6999d13aca25e33515210abaf1"`);
        await queryRunner.query(`DROP TABLE "post_likes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c954d0d1472ab3e9f68d19b19f"`);
        await queryRunner.query(`DROP TABLE "destinations"`);
        await queryRunner.query(`DROP TYPE "public"."destinations_imagesource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."destinations_province_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78c7117b54e48f4a8ae2acb054"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c9bab3324bd8bcd18a0184fc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd9bb7e79c38564ff28d5674a8"`);
        await queryRunner.query(`DROP TABLE "trip_route"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3aa10c29ea4e61a830362bd25"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3dd7c4dfa4c2fe57fa5894ab5"`);
        await queryRunner.query(`DROP TABLE "spots"`);
        await queryRunner.query(`DROP TYPE "public"."spots_imagesource_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_374668b8bdcb37409c5a47acfc"`);
        await queryRunner.query(`DROP TABLE "trip_route_day"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98346f7a760e7de5ee79c9325e"`);
        await queryRunner.query(`DROP TABLE "trip_route_item"`);
        await queryRunner.query(`DROP TYPE "public"."trip_route_item_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0a7140c8d15ee5cdd0b36e1de"`);
        await queryRunner.query(`DROP TABLE "bookmark"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4367f08021b501ba78f98ae01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8770bd9030a3d13c5f79a7d2e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e8d7c49f218ebb14314fdb374"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_668c9fb892f2accb872670c7b1"`);
        await queryRunner.query(`DROP TABLE "post_image"`);
    }

}
